name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: nestjs-api

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t $IMAGE_NAME --target=test .

    - name: Run Test
      run: docker run $IMAGE_NAME
