name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull marcospmcdev/movies-api:latest

      - name: Delete old container
        run: sudo docker rm -f movies-api-container || true
      
      - name: Run Docker container
        run: sudo docker run -d -p 80:3000 --name movies-api-container marcospmcdev/movies-api
